# Source: jx3-gohttp-3/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-12T15:18:16Z"
  deletionTimestamp: null
  name: 'jx3-gohttp-3-0.0.1'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.1
      sha: 894596e77736d10381e9cc051bb3658146cd755f
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 68644994b002b365e5b63614f1de17fd05857028
    - author:
        email: piontec@gmail.com
        name: Łukasz Piątkowski
      branch: master
      committer:
        email: piontec@gmail.com
        name: Łukasz Piątkowski
      message: |
        chore: Jenkins X build pack
      sha: f5928dd6cc8fa2d6ca696e4624d55bb85cd0ec78
  gitHttpUrl: https://github.com/piontec/jx3-gohttp-3
  gitOwner: piontec
  gitRepository: jx3-gohttp-3
  name: 'jx3-gohttp-3'
  releaseNotesURL: https://github.com/piontec/jx3-gohttp-3/releases/tag/v0.0.1
  version: v0.0.1
status: {}
